
const FRETE = [
    {   id:'consumirnolocal', 
        nome:'Consumir no Local',
        valor: 0, 
        categoria: 'AÇAIS',
        input: 'radio',
        tipo: 'localdeconsumo',
    },
    {   id:'frete', 
        nome:'Frete',
        valor: 5, 
        categoria: 'AÇAIS',
        input: 'radio',
        tipo: 'localdeconsumo',
    }
]

const AÇAIS = [
    {   id:'copo200ml', 
        nome:'Copo 200ml',
        valor: 10, 
        categoria: 'AÇAIS',
        input: 'radio',
        tipo: 'produto',
    },
    {   id:'copo300ml', 
        nome:'Copo 300ml',
        valor: 16, 
        categoria: 'AÇAIS',
        input: 'radio',
        tipo: 'produto',
    },
    {   id:'copo500ml', 
        nome:'Copo 500ml',
        valor: 20, 
        categoria: 'AÇAIS',
        input: 'radio',
        tipo: 'produto',
    },
]

const BEBIDAS = [
    {   id:'aguacomgas',
        nome:'Água com gás',
        valor: 4, 
        categoria: 'BEBIDAS',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id:'aguasemgas',
        nome:'Água sem gás',
        valor: 3, 
        categoria: 'BEBIDAS',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id:'guarana300ml',
        nome:'Guaraná 300ml',
        valor: 5, 
        categoria: 'BEBIDAS',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id:'cocacola300ml',
        nome:'Coca-Cola 300ml',
        valor: 5, 
        categoria: 'BEBIDAS',
        input: 'checkbox',
        tipo: 'produto',
    },
]

const SALGADOS = [
    {   id:'refinatachurrasco',
        nome:'Refinata Churrasco',
        valor: 4, 
        categoria:'SALGADOS',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id: 'refinatacostelinha' , 
        nome:'Refinata Costelinha',     
        valor: 4, 
        categoria: 'SALGADOS',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id: 'cronycebolaesalca' , 
        nome:'Crony Cebola e Salça',
        valor: 4, 
        categoria: 'SALGADOS',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id: 'refinatapicanhaealho' , 
        nome:'Refinata Picanha e Alho',
        valor: 4, 
        categoria: 'SALGADOS',
        input: 'checkbox',
        tipo: 'produto',
    },
]

const DOCES = [
    {   id: 'kitkat',
        nome:'KitKat',
        valor: 4,   
        categoria: 'DOCES',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id: 'pirulitobig', 
        nome:'Pirulito Big',
        valor: 0.5, 
        categoria: 'DOCES',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id: 'pacoca', 
        nome:'Paçoca',
        valor: 0.5, 
        categoria: 'DOCES',
        input: 'checkbox',
        tipo: 'produto',
    },
    {   id: 'balinhas', 
        nome:'Balinhas',
        valor: 0.2, 
        categoria: 'DOCES',
        input: 'checkbox',
        tipo: 'produto',
    },    
]


const ADICIONAIS = [
    {   id: 'leitecondensado',
        nome:'leite condensado',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'caldadechocolate',
        nome:'calda de chocolate',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'caldademorango',
        nome:'calda de morango',
        valor: 1,
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'morango',
        nome:'morango',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'uva',
        nome:'uva',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'banana',
        nome:'banana',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'ovomaltine',
        nome:'ovomaltine',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'leiteninho',
        nome:'leite ninho',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'pacoca',
        nome:'pacoca',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'granola',
        nome:'granola',
        valor: 1, 
        premium: false,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'mem',
        nome:'mem',
        valor: 3, 
        premium: true ,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'kitkat',
        nome:'kitkat',
        valor: 4, 
        premium: true ,
        tipo: 'adicional',
        input: 'checkbox',
    },
    {   id: 'nutella',
        nome:'nutella',
        valor: 5, 
        premium: true ,
        tipo: 'adicional',
        input: 'checkbox',
    },
]


const CATEGORIAS = [
    FRETE , AÇAIS, DOCES, BEBIDAS, SALGADOS
]

const DB_PRODUTOS_E_ADICIONAIS = [
    FRETE , AÇAIS, DOCES, BEBIDAS, SALGADOS, ADICIONAIS
]


function f_ADICIONAIS(){
    localStorage.setItem("ADICIONAIS", JSON.stringify(ADICIONAIS))
}f_ADICIONAIS()


function f_CATEGORIAS(){
    localStorage.setItem("CATEGORIAS", JSON.stringify(CATEGORIAS))
}f_CATEGORIAS()









